### ISSUE TITLE
Can not compile with gcc 5.2

### ISSUE THREAD

**Issue by jb-alvarado** [lu-zero/mfx_dispatch#15]
Hello,
since a time we use your lib in our msys2 build script ( https://github.com/jb-alvarado/media-autobuild_suite ). But now msys2 have change to gcc 5.2 and since this time we are not able anymore to compile mfx.

Here is the error message:
```
[...]
libtool: compile:  g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.16\" "-DPACKAGE_STRING=\"libmfx 1.16\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libmfx\" -DVERSION=\"1.16\" -DMFX_HAVE_WINDOWS=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I./include -DMINGW_HAS_SECURE_API=1 -I/local32/include -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -I/local32/include -mms-bitfields -mthreads -mtune=generic -pipe -MT src/main.lo -MD -MP -MF src/.deps/main.Tpo -c src/main.cpp -o src/main.o
In file included from D:/_System/msys2-64_Juni2015/msys64/mingw32/i686-w64-mingw32/include/stdio.h:991:0,
                 from src/mfx_plugin_hive.h:39,
                 from src/mfx_load_plugin.h:34,
                 from src/mfx_dispatcher.h:39,
                 from src/main.cpp:31:
D:/_System/msys2-64_Juni2015/msys64/mingw32/i686-w64-mingw32/include/sec_api/stdio_s.h:32:51: error: conflicting declaration of 'int sscanf(const char*, const char*, ...)' with 'C' linkage
   int __cdecl sscanf_s(const char*,const char*,...);
                                                   ^
In file included from src/mfx_plugin_hive.h:39:0,
                 from src/mfx_load_plugin.h:34,
                 from src/mfx_dispatcher.h:39,
                 from src/main.cpp:31:
D:/_System/msys2-64_Juni2015/msys64/mingw32/i686-w64-mingw32/include/stdio.h:227:5: note: previous declaration with 'C++' linkage
 int sscanf(const char *__source, const char *__format, ...)
     ^
Makefile:637: die Regel für Ziel „src/main.lo“ scheiterte
make: *** [src/main.lo] Fehler 1
```
Is there something what we can do, or needs this a change in your code?

Regards
Jonathan

**Comment by lu-zero** [comment]
Would work better with English, let me see why the macro used to match windows is not working anymore

**Comment by lu-zero** [comment]
```
#ifdef __GNUC__
#define  sscanf_s  sscanf
#define  swscanf_s swscanf
#endif
```
that's the problem.

**Comment by lu-zero** [comment]
Please try now and report back.

**Comment by wiiaboo** [comment]
At least now it fails on both MingW GCC 4.9.2 and 5.2. 

GCC 4.9.2:
```
depbase=`echo src/mfx_plugin_hive.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.16\" -DPACKAGE_STRING=\"libmfx\ 1.16\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libmfx\" -DVERSION=\"1.16\" -DMFX_HAVE_WINDOWS=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.  -I./include -DMINGW_HAS_SECURE_API=1 -I/local64/include -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1  -I/local64/include -mms-bitfields -mthreads -mtune=generic -pipe -MT src/mfx_plugin_hive.lo -MD -MP -MF $depbase.Tpo -c -o src/mfx_plugin_hive.lo src/mfx_plugin_hive.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.16\" "-DPACKAGE_STRING=\"libmfx 1.16\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libmfx\" -DVERSION=\"1.16\" -DMFX_HAVE_WINDOWS=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I./include -DMINGW_HAS_SECURE_API=1 -I/local64/include -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -I/local64/include -mms-bitfields -mthreads -mtune=generic -pipe -MT src/mfx_plugin_hive.lo -MD -MP -MF src/.deps/mfx_plugin_hive.Tpo -c src/mfx_plugin_hive.cpp -o src/mfx_plugin_hive.o
src/mfx_plugin_hive.cpp: In constructor 'MFX::MFXPluginsInFS::MFXPluginsInFS(mfxVersion)':
src/mfx_plugin_hive.cpp:279:88: error: 'swscanf_s' was not declared in this scope
             if (1 != swscanf_s(find_data.cFileName + charsPermfxU8 * i, L"%2x", &hexNum))
                                                                                        ^
src/mfx_plugin_hive.cpp: In member function 'bool MFX::MFXPluginsInFS::ParseKVPair(msdk_disp_char*, msdk_disp_char*, MFX::PluginDescriptionRecord&)':
src/mfx_plugin_hive.cpp:380:50: error: 'swscanf_s' was not declared in this scope
         if (0 == swscanf_s(value, L"%d", &version))
                                                  ^
src/mfx_plugin_hive.cpp:400:53: error: 'swscanf_s' was not declared in this scope
         if (0 == swscanf_s(value, L"%d", &APIversion))
                                                     ^
Makefile:637: recipe for target 'src/mfx_plugin_hive.lo' failed
make: *** [src/mfx_plugin_hive.lo] Error 1
```

GCC 5.2:
```
$ make
depbase=`echo src/mfx_plugin_hive.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.16\" -DPACKAGE_STRING=\"libmfx\ 1.16\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libmfx\" -DVERSION=\"1.16\" -DMFX_HAVE_WINDOWS=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.  -I./include -DMINGW_HAS_SECURE_API=1 -I/local64/include -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1  -I/local64/include -mms-bitfields -mthreads -mtune=generic -pipe -MT src/mfx_plugin_hive.lo -MD -MP -MF $depbase.Tpo -c -o src/mfx_plugin_hive.lo src/mfx_plugin_hive.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.16\" "-DPACKAGE_STRING=\"libmfx 1.16\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libmfx\" -DVERSION=\"1.16\" -DMFX_HAVE_WINDOWS=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I./include -DMINGW_HAS_SECURE_API=1 -I/local64/include -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -I/local64/include -mms-bitfields -mthreads -mtune=generic -pipe -MT src/mfx_plugin_hive.lo -MD -MP -MF src/.deps/mfx_plugin_hive.Tpo -c src/mfx_plugin_hive.cpp -o src/mfx_plugin_hive.o
src/mfx_plugin_hive.cpp: In constructor 'MFX::MFXPluginsInFS::MFXPluginsInFS(mfxVersion)':
src/mfx_plugin_hive.cpp:279:88: error: 'swscanf_s' was not declared in this scope
             if (1 != swscanf_s(find_data.cFileName + charsPermfxU8 * i, L"%2x", &hexNum))
                                                                                        ^
src/mfx_plugin_hive.cpp: In member function 'bool MFX::MFXPluginsInFS::ParseKVPair(msdk_disp_char*, msdk_disp_char*, MFX::PluginDescriptionRecord&)':
src/mfx_plugin_hive.cpp:380:50: error: 'swscanf_s' was not declared in this scope
         if (0 == swscanf_s(value, L"%d", &version))
                                                  ^
src/mfx_plugin_hive.cpp:400:53: error: 'swscanf_s' was not declared in this scope
         if (0 == swscanf_s(value, L"%d", &APIversion))
                                                     ^
Makefile:637: recipe for target 'src/mfx_plugin_hive.lo' failed
make: *** [src/mfx_plugin_hive.lo] Error 1
```

**Comment by lu-zero** [comment]
I guess a solution is to drop the "secure" variants completely

**Comment by wiiaboo** [comment]
Confirm it's working on both 4.9.2 and 5.2 with the latest commit. Thanks

**Comment by lu-zero** [comment]
Good to know =)
